### ISSUE TITLE
CUDA-aware runtime error

### ISSUE THREAD

**Issue by moravveji** [NVIDIA-developer-blog/code-samples#19]
Hi all,
First, thanks a lot of sharing the very valuable code bases here.

I am trying to run the cuda-aware MPI example on a compute node with a P100 device attached. The example's been made with the following modules (esp. CUDA 10 and OpenMPI 4):

Currently Loaded Modules (list is jammed after copy-paste):
  1) GCCcore/6.4.0                 4) zlib/1.2.11-GCCcore-6.4.0      7) libxml2/2.9.7-GCCcore-6.4.0      10) CUDA/10.0.130
  2) binutils/2.28-GCCcore-6.4.0   5) numactl/2.0.11-GCCcore-6.4.0   8) libpciaccess/0.14-GCCcore-6.4.0  11) OpenMPI/4.0.0-GCC-6.4.0-2.28
  3) GCC/6.4.0-2.28                6) XZ/5.2.3-GCCcore-6.4.0         9) hwloc/2.0.2-GCCcore-6.4.0

Below is the error message I receive after executing the first example:

`cuda-aware-mpi-example$ mpiexec -np 2 bin/jacobi_cuda_normal_mpi -t 2 1
Topology size: 2 x 1
Local domain size (current node): 4096 x 4096
Global domain size (all nodes): 8192 x 4096
Error: CUDA result "CUDA driver version is insufficient for CUDA runtime version" for call "cudaGetDeviceCount(&devCount)" in file "CUDA_Normal_MPI.c" at line 55. Terminating...
Error: CUDA result "CUDA driver version is insufficient for CUDA runtime version" for call "cudaGetDeviceCount(&devCount)" in file "CUDA_Normal_MPI.c" at line 55. Terminating...
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[15358,1],0]
  Exit code:    255
`
Despite I am using CUDA/10.0.130, the most recent version of that is 10.1; hence, my CUDA module is not that old. However, the error complains about "CUDA driver version is insufficient".

Do you have any idea what might have been wrong?

Regards,
Ehsan

**Comment by jirikraus** [comment]
Hi Ehsan,

the error message you past is not related to the code you tried I am therefore closing this issue. The error message indicates a system setup issue. For CUDA 10.0.130 you need at least a 410.48 CUDA driver (see https://docs.nvidia.com/deploy/cuda-compatibility/index.html). Please check your CUDA driver version with `nvidia-smi` it reports the driver version at the top:

```
nvidia-smi | grep "Driver Version"
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
```

You can then either use a older CUDA version supported by your Driver Version or upgrade your Driver Version. 

Hope this helps

Jiri
