### ISSUE TITLE
CUDA-aware MPI example complains about CUDA runtime version

### ISSUE THREAD

**Issue by moravveji** [NVIDIA-developer-blog/code-samples#20]
Hi,

Firstly, thanks for sharing the great examples with the community. 
I am interested in starting with the CUDA-aware MPI example to test our GPU nodes, where each node has 4xP100 devices. 

I recently installed OpenMPI v. 4.0.0 together with CUDA/10.0.130. The nvidia driver is version 418.40.04. The example is compiled using these modules. 
Now, I would like to test the node ... 

`bin$ mpirun -np 4 jacobi_cuda_normal_mpi -t 2 2
Topology size: 2 x 2
Local domain size (current node): 4096 x 4096
Global domain size (all nodes): 8192 x 8192
Error: CUDA result "CUDA driver version is insufficient for CUDA runtime version" for call "cudaGetDeviceCount(&devCount)" in file "CUDA_Normal_MPI.c" at line 55. Terminating...
Error: CUDA result "CUDA driver version is insufficient for CUDA runtime version" for call "cudaGetDeviceCount(&devCount)" in file "CUDA_Normal_MPI.c" at line 55. Terminating...
Error: CUDA result "CUDA driver version is insufficient for CUDA runtime version" for call "cudaGetDeviceCount(&devCount)" in file "CUDA_Normal_MPI.c" at line 55. Terminating...
Error: CUDA result "CUDA driver version is insufficient for CUDA runtime version" for call "cudaGetDeviceCount(&devCount)" in file "CUDA_Normal_MPI.c" at line 55. Terminating...
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[41647,1],2]
  Exit code:    255
--------------------------------------------------------------------------
`

Do you have any idea why this goes wrong?

With best regards,
Ehsan

**Comment by jirikraus** [comment]
Hi Ehsan,

the error message says this is still the same issue you filed some weeks ago: https://github.com/NVIDIA-developer-blog/code-samples/issues/19. 

Can you verify with nvidia-smi that the driver version is indeed the expected 418.40.04 the output you should see should be similar to this:

```shell
$ nvidia-smi | grep Version
| NVIDIA-SMI 418.40       Driver Version: 418.40       CUDA Version: 10.1     |
```

if that is the case please check that `deviceQuery` from the CUDA samples works and reports a CUDA Driver Version of 10.1. You should see an output similar to:

```shell
samples/1_Utilities/deviceQuery$ ./deviceQuery | grep "CUDA Driver Version"
  CUDA Driver Version / Runtime Version          10.1 / 10.1
  CUDA Driver Version / Runtime Version          10.1 / 10.1
deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 10.1, CUDA Runtime Version = 10.1, NumDevs = 2
```

This is unrelated to the code sample so I am closing this issue.

Thanks

Jiri

**Comment by moravveji** [comment]
Thanks Jiri for your comment. 
You were true about the incompatibility of the driver and runtime versions. In my case, the former was 10.1, while the latter was 10.0. So, I reinstalled CUDA/10.1, and now both are compatible (the same version).
Thanks a lot
Ehsan
