### ISSUE TITLE
memtype_cache.c:137  UCX  WARN  destroying inuse address

### ISSUE THREAD

**Issue by moravveji** [NVIDIA-developer-blog/code-samples#21]
Hey guys,

I have installed OpeMPI v.3.1.4 with UCX, gdrcopy and CUDA from source. When I load the module, here is the list of dependencies:

![image](https://user-images.githubusercontent.com/6280576/57525142-3c5c1880-732a-11e9-9135-1723480b47f9.png)

When I try the `jacobi_cuda_normal_mpi` with 4 processes, I get an output, and a lot of (similar) warning messages at the bottom. The warnings look like this (full stdout/stderr attached below):
```bash
[1557488926.059031] [r24g38:186803:0]  memtype_cache.c:137  UCX  WARN  destroying inuse address:0x2b11a8000000 
```
Shall I be concerned about UCX? Is there a way I would inspect this further, and fix the issue, so the the stderr stays clean?

Kindest regards,
Ehsan

[log.txt](https://github.com/NVIDIA-developer-blog/code-samples/files/3166331/log.txt)

**Comment by jirikraus** [comment]
Hi Ehsan,

I would suggest that you discuss your issue with the OpenMPI developers. The OpenMPI Users Mailing list is probably a good start: https://www.open-mpi.org//community/lists/ompi.php 

I am closing this issue as it is not related to the code sample but to the MPI stack you are using.

Thanks

Jiri
